FROM ubuntu:16.04
MAINTAINER couchdb@gmail.com

# Install and configure CouchDB 1.6.0
RUN apt-get install -y --force-yes && \
    erlang-dev \
    erlang-manpages \
    erlang-base-hipe \
    erlang-eunit \
    erlang-nox \
    erlang-xmerl \
    erlang-inets \
    libmozjs185-dev \
    libicu-dev \
    libcurl4-gnutls-dev \
    libtool && \
    cd /tmp && \
    wget http://mirror.sdunix.com/apache/couchdb/source/1.6.0/apache-couchdb-1.6.0.tar.gz && \
    tar xzvf apache-couchdb-1.6.0.tar.gz && \
    cd apache-couchdb-1.6.0 && \
    ./configure && \
    make && \
    make install && \
    sed -e 's/^bind_address = .*$/bind_address = 0.0.0.0/' -i /usr/local/etc/couchdb/default.ini && \
    sed -e 's/^database_dir = .*$/database_dir = \/data/' -i /usr/local/etc/couchdb/default.ini && \
    sed -e 's/^view_index_dir = .*$/view_index_dir = \/data/' -i /usr/local/etc/couchdb/default.ini && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Command to run
CMD [""]

# Expose listen port
EXPOSE 5984
